#!/bin/sh

if [ $# -ne 2 ];
then
    echo 'Usage: getsecretsforconsumerkey [DBNAME] [CONSUMERKEY]'
    exit 0
fi

DBNAME=$1
KEY=$2

psql ${DBNAME} -c "SELECT t2.value \
FROM mdl_lti_types_config t1 \
JOIN mdl_lti_types_config t2 ON t1.typeid = t2.typeid \
JOIN mdl_lti_types type ON t2.typeid = type.id \
WHERE t1.name = 'resourcekey' \
AND t1.value = '${KEY}' \
AND t2.name = 'password' \
AND type.state = 1 \
UNION \
SELECT password AS value \
FROM mdl_lti \
WHERE resourcekey = '${KEY}'"
